name: test_coverage

on: [pull_request]
          #run specific jobs when specific files are updated.
          #https://github.community/t/how-to-execute-jobs-if-folder-updated-recursive/117344/5

jobs:
  check:
    name: Check changed files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: check files
        id: check_files
        run: |
          echo "=============== list changed files ==============="
          git diff --name-only ${GITHUB_BASE_REF} HEAD
          
          echo "========== check paths of changed files =========="
          git diff --name-only ${GITHUB_BASE_REF} HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != "subdir/env1/"* ]]; then
              echo "This file is not under the directory 'subdir/env1'."
              echo "::set-output name=run_job::false"
              break
            else
              echo "::set-output name=run_job::true"
            fi
          done < files.txt
  pod-lib-lint-database:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    runs-on: macOS-latest

    strategy:
      matrix:
        target: [ios, tvos, macos]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Build and test
      run: |
        if [ -d "/Users/runner/Library/Developer/Xcode/DerivedData" ]; then
        rm -r /Users/runner/Library/Developer/Xcode/DerivedData/*
        fi
        scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb FirebaseDatabase.podspec --platforms=${{ matrix.target }} --test-specs=unit
        find /Users/runner/Library/Developer/Xcode/DerivedData -regex ".*/.*\.xcresult" -exec xcrun xccov view --report {} \;

  pod-lib-lint-function:
    # Don't run on private repo unless it is a PR.
    if: (github.repository == 'Firebase/firebase-ios-sdk' && github.event_name == 'schedule') || github.event_name == 'pull_request'
    runs-on: macOS-latest

    strategy:
      matrix:
        target: [ios, tvos, macos]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bundler
      run: scripts/setup_bundler.sh
    - name: Build and test
      run: |
        if [ -d "/Users/runner/Library/Developer/Xcode/DerivedData" ]; then
        rm -r /Users/runner/Library/Developer/Xcode/DerivedData/*
        fi
        scripts/third_party/travis/retry.sh scripts/pod_lib_lint.rb FirebaseFunctions.podspec --platforms=${{ matrix.target }} --test-specs=unit
        find /Users/runner/Library/Developer/Xcode/DerivedData -regex ".*/.*\.xcresult" -exec xcrun xccov view --report {} \;
